apiVersion: apps/v1
kind: Deployment
metadata:
  name: mundose
  labels:
    app: mundose
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mundose
  template:
    metadata:
      labels:
        app: mundose
    spec:
      containers:
      - name: mundose
        image: kiritian/pin-app:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
