apiVersion: apps/v1
kind: Deployment
metadata:
  name: mundose-app
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mundose-app
  template:
    metadata:
      labels:
        app: mundose-app
    spec:
      containers:
        - name: app
          image: kiritian/pin-app:1.0.0
          ports:
            - name: web
              containerPort: 3001   
              protocol: TCP
