kind: Service
apiVersion: v1
metadata:
  name: mundose-loadbalancer
  namespace: jenkins       
spec:
  type: LoadBalancer       
  selector:
    app: mundose-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web
