apiVersion: v1
kind: Service
metadata:
  name: mundose-service
  labels:
    app: mundose
spec:
  type: LoadBalancer
  selector:
    app: mundose-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3001
